version: '3.8'
services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=navingrg
      - MONGO_INITDB_ROOT_PASSWORD=navingrg
      - MONGO_INITDB_DATABASE=mongoDb